-- ==============================================================================
-- BHAGWA BACKEND MIGRATION: 20260816000004_auth_and_user_identity.sql
-- ==============================================================================

-- 1. ADD NUMERIC USER ID & EXTRA PROFILE FIELDS TO PROFILES TABLE
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS user_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  ADD COLUMN IF NOT EXISTS login_method TEXT NOT NULL DEFAULT 'skip',
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS is_anonymous BOOLEAN NOT NULL DEFAULT FALSE;

-- Create index on numeric user_id
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_login_method ON public.profiles(login_method);

-- 2. UPDATE TRIGGER FUNCTION TO PROPERLY EXTRACT AUTH PROVIDER & METADATA
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_profile_id UUID;
  v_login_method TEXT;
  v_is_anonymous BOOLEAN;
  v_display_name TEXT;
BEGIN
  -- Determine provider from auth metadata
  v_login_method := COALESCE(NEW.raw_app_meta_data->>'provider', 'skip');
  IF v_login_method = 'anonymous' THEN
    v_login_method := 'skip';
    v_is_anonymous := TRUE;
  ELSE
    v_is_anonymous := COALESCE((NEW.raw_user_meta_data->>'is_anonymous')::boolean, FALSE);
  END IF;

  v_display_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'name',
    CASE WHEN v_is_anonymous THEN 'Guest Devotee' ELSE 'Devotee' END
  );

  INSERT INTO public.profiles (
    auth_user_id,
    email,
    phone_number,
    display_name,
    avatar_url,
    login_method,
    is_anonymous
  )
  VALUES (
    NEW.id,
    NEW.email,
    NEW.phone,
    v_display_name,
    NEW.raw_user_meta_data->>'avatar_url',
    v_login_method,
    v_is_anonymous
  )
  ON CONFLICT (auth_user_id) DO UPDATE SET
    last_active_at = NOW()
  RETURNING id INTO v_profile_id;

  -- Create default user preferences if not existing
  INSERT INTO public.user_preferences (user_id)
  VALUES (v_profile_id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. SEED LOGIN OPTIONS IN APP_SETTINGS
INSERT INTO public.app_settings (setting_key, setting_value, description) VALUES
('auth.google_enabled', 'true'::jsonb, 'Toggle visibility of Continue with Google login option in mobile app'),
('auth.phone_enabled', 'true'::jsonb, 'Toggle visibility of Phone OTP login option in mobile app'),
('auth.skip_enabled', 'true'::jsonb, 'Toggle visibility of Continue without Login option in mobile app')
ON CONFLICT (setting_key) DO NOTHING;
